name: Build and Deploy Container

on:
  push:
    branches:
      - main  # Make sure this matches your default branch name (main or master)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Log in to Azure Container Registry
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t ${{ secrets.REGISTRY_URL }}/student-performance-prediction:latest .
        docker push ${{ secrets.REGISTRY_URL }}/student-performance-prediction:latest

    - name: Deploy Container to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'student-performance-prediction'
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        images: '${{ secrets.REGISTRY_URL }}/student-performance-prediction:latest'
